name: CICD for GO

on: 
  push: 
    branches: [main]
    
  pull_request: 
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout my codes
        uses: actions/checkout@v2
      - name: Setup Go 
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - name: Check Go Version
        run: |
          go version
      - name: Install dependencies
        run: |
          go get github.com/tebeka/go2xunit
      - if: ${{success()}}
        name: Install Goblin
        run: |
          go get github.com/franela/goblin
      - if: ${{success()}}
        name: Test Goblin
        run: |
          go test -v
          go test -v | go2xunit >report.xml
      - if: ${{failure()}}
        name: Create Issues
        uses: nashmaniac/create-issue-action@v1.1 
        with:
          title: Build Failed
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: worflow-failed
          body: Workflow failed for commit ${{github.sha}}
      - if: ${{success()}}
        name: Display test information
        uses: EnricoMi/publish-unit-test-result-action@v1.5
        with: 
          github_token: ${{secrets.GITHUB_TOKEN}}
          files: report.xml
  
    
