name: CICD for GO

on: 
  push: 
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout my codes
        uses: actions/checkout@v2
      - name: Setup Go 
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - name: Check Go Version
        run: |
          go version
       
    
    
