name: Release 

on:
  create:
    tags:
      - v*
      
jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out codes
        uses: actions/checkout@v2
      
      - name: Setup Go Environment
        uses: actions/setup-go@v2
        with:
            go-version: '1.15'
            
      - name: Create go module
        run: |
          go mod init
          go mod tidy
      
      - name: Validate Go Releaser configuration
        uses: docker://goreleaser/goreleaser:latest
        with:
          arg: check
          
      - name: Create release on Github
        uses: docker://goreleaser/goreleaser:latest
        with:
          arg: release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
